ark info: "ark info "
ark start: "ark start "
ark start local: "ark start -l "
ark rollback: "ark rollback "
ark deploys: "ark deploys "
ark stop: "ark stop "
ark freeze: "ark freeze "
ark unfreeze: "ark unfreeze "
ark restart: "ark restart "
ark scale: "ark scale "
ark suspend: "ark suspend "
ark config: "ark config "

ee prod: " -e production "
ee dev: " -e clever-dev "

pick a bot sharpies: "@pickabot assign sharing-apis "
